version: '3'
services:
  datadog-agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=<YOUR_API_KEY>
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    networks:
      - agent-network

  app:
    build: .
    environment:
      - DATADOG_TRACE_DEBUG=true
    ports:
      - "80:80"
    networks:
      - agent-network

networks:
  agent-network:
    # Use a custom driver
    #driver: default
